version: 2
jobs:
  build-node8:
    docker:
      - image: node:8
    working_directory: ~/w
    steps:
      - checkout
      - run: yarn global add gulp cypress-cli
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn tslint
      - run: yarn test
  publish:
    docker:
      - image: node:8
    working_directory: ~/w
    steps:
     - checkout
     - deploy:
          name: Publish to npm.org
          command: ls -l

workflows:
  version: 2
  build:
    jobs:
      - build-node8
      - publish:
          requires:
            - build-node8
          filters:
            branches:
              only: circleci2
